name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:

jobs:
  cache-dependencies:
    name: Cache dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/cache-dependencies.yaml@composite-actions

  precompile-assets:
    name: Precompile Rails assets
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/precompile-rails-assets.yaml@composite-actions

  security-analysis:
    name: Security Analysis
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/brakeman.yaml@composite-actions

  lint-scss:
    name: Lint SCSS
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/stylelint.yaml@composite-actions

  lint-javascript:
    name: Lint JavaScript
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/standardx.yaml@composite-actions

  lint-ruby:
    name: Lint Ruby
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/rubocop.yaml@composite-actions

  test-javascript:
    name: Test JavaScript
    needs: precompile-assets
    uses: alphagov/govuk-infrastructure/.github/workflows/jasmine.yaml@composite-actions
    with:
      useWithRails: true

  test-ruby:
    name: Test Ruby
    needs: precompile-assets
    uses: alphagov/govuk-infrastructure/.github/workflows/run-command.yaml@composite-actions
    with:
      enableNodeJS: true
      enableMySQL: true
      enableRedis: true
      extraSystemDependencies: 'ghostscript'
      checkoutContentSchemas: true
      commands: |
        bundle exec rails db:setup
        bundle exec rails test

  integration-tests:
    name: Integration tests
    needs: precompile-assets
    uses: alphagov/govuk-infrastructure/.github/workflows/run-command.yaml@composite-actions
    with:
      enableNodeJS: true
      enableMySQL: true
      enableRedis: true
      extraSystemDependencies: 'ghostscript'
      commands: |
        bundle exec rails db:setup
        bundle exec rails cucumber

