name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:

jobs:
  cache-dependencies:
    name: Cache dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/cache-dependencies.yaml@main

  precompile-assets:
    name: Precompile Rails assets
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/precompile-rails-assets.yaml@main

  security-analysis:
    name: Security Analysis
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/brakeman.yaml@main

  lint-scss:
    name: Lint SCSS
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/stylelint.yaml@main
    with:
      files: "app/assets/stylesheets/"

  lint-javascript:
    name: Lint JavaScript
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/standardx.yaml@main
    with:
      files: "'app/assets/javascripts/**/*.js' 'spec/javascripts/**/*.js'"

  lint-ruby:
    name: Lint Ruby
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/rubocop.yaml@main

  test-javascript:
    name: Test JavaScript
    needs: precompile-assets
    uses: alphagov/govuk-infrastructure/.github/workflows/jasmine.yaml@main
    with:
      useWithRails: true

  test-ruby:
    name: Test Ruby
    needs: precompile-assets
    runs-on: ubuntu-latest
    steps:
      - name: Setup MySQL
        id: setup-mysql
        uses: alphagov/govuk-infrastructure/.github/actions/setup-mysql@main

      - name: Setup Redis
        uses: alphagov/govuk-infrastructure/.github/actions/setup-redis@main

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout Publishing API (for Content Schemas)
        uses: actions/checkout@v3
        with:
          repository: alphagov/publishing-api
          ref: deployed-to-production
          path: vendor/publishing-api

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: alphagov/govuk-infrastructure/.github/actions/setup-node@main

      - name: Precompile assets
        uses: alphagov/govuk-infrastructure/.github/actions/precompile-rails-assets@main

      - name: Initialize database
        env:
          RAILS_ENV: test
          TEST_DATABASE_URL: ${{ steps.setup-mysql.outputs.db-url }}
        run: bundle exec rails db:setup

      - name: Run Minitest
        env:
          RAILS_ENV: test
          GOVUK_CONTENT_SCHEMAS_PATH: vendor/publishing-api/content_schemas
          TEST_DATABASE_URL: ${{ steps.setup-mysql.outputs.db-url }}
        run: bundle exec rake test

  integration-tests:
    name: Integration tests
    needs: precompile-assets
    runs-on: ubuntu-latest
    steps:
      - name: Setup MySQL
        id: setup-mysql
        uses: alphagov/govuk-infrastructure/.github/actions/setup-mysql@main

      - name: Setup Redis
        uses: alphagov/govuk-infrastructure/.github/actions/setup-redis@main

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: alphagov/govuk-infrastructure/.github/actions/setup-node@main

      - name: Precompile assets
        uses: alphagov/govuk-infrastructure/.github/actions/precompile-rails-assets@main

      - name: Initialize database
        env:
          RAILS_ENV: test
          TEST_DATABASE_URL: ${{ steps.setup-mysql.outputs.db-url }}
        run: bundle exec rails db:setup

      - name: Run cucumber
        env:
          RAILS_ENV: test
          TEST_DATABASE_URL: ${{ steps.setup-mysql.outputs.db-url }}
        run: bundle exec rails cucumber

