name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:

jobs:
  cache-dependencies:
    name: Cache dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/cache-dependencies.yaml@composite-actions

  precompile-assets:
    name: Precompile Rails assets
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/precompile-rails-assets.yaml@composite-actions

  security-analysis:
    name: Security Analysis
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/brakeman.yaml@composite-actions

  lint-scss:
    name: Lint SCSS
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/stylelint.yaml@composite-actions

  lint-javascript:
    name: Lint JavaScript
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/standardx.yaml@composite-actions

  lint-ruby:
    name: Lint Ruby
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/rubocop.yaml@composite-actions

  test-javascript:
    name: Test JavaScript
    needs: precompile-assets
    uses: alphagov/govuk-infrastructure/.github/workflows/jasmine.yaml@composite-actions
    with:
      useWithRails: true

  test-ruby:
    name: Test Ruby
    needs: precompile-assets
    runs-on: ubuntu-latest
    steps:
      - name: Setup MySQL
        id: setup-mysql
        uses: alphagov/govuk-infrastructure/.github/actions/setup-mysql@composite-actions

      - name: Setup Redis
        uses: alphagov/govuk-infrastructure/.github/actions/setup-redis@composite-actions

      - name: Install additional system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ghostscript

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout Publishing API (for Content Schemas)
        uses: actions/checkout@v3
        with:
          repository: alphagov/publishing-api
          ref: deployed-to-production
          path: vendor/publishing-api

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: alphagov/govuk-infrastructure/.github/actions/setup-node@composite-actions

      - name: Initialize database
        env:
          RAILS_ENV: test
          TEST_DATABASE_URL: ${{ steps.setup-mysql.outputs.db-url }}
        run: bundle exec rails db:setup

      - name: Run Minitest
        env:
          RAILS_ENV: test
          GOVUK_CONTENT_SCHEMAS_PATH: vendor/publishing-api/content_schemas
          TEST_DATABASE_URL: ${{ steps.setup-mysql.outputs.db-url }}
        run: bundle exec rake test

  integration-tests:
    name: Integration tests
    needs: precompile-assets
    runs-on: ubuntu-latest
    steps:
      - name: Setup MySQL
        id: setup-mysql
        uses: alphagov/govuk-infrastructure/.github/actions/setup-mysql@composite-actions

      - name: Setup Redis
        uses: alphagov/govuk-infrastructure/.github/actions/setup-redis@composite-actions

      - name: Install additional system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ghostscript

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: alphagov/govuk-infrastructure/.github/actions/setup-node@composite-actions

      - name: Precompile Rails assets
        uses: alphagov/govuk-infrastructure/.github/actions/precompile-rails-assets@composite-actions

      - name: Initialize database
        env:
          RAILS_ENV: test
          TEST_DATABASE_URL: ${{ steps.setup-mysql.outputs.db-url }}
        run: bundle exec rails db:setup

      - name: Run Cucumber
        env:
          RAILS_ENV: test
          TEST_DATABASE_URL: ${{ steps.setup-mysql.outputs.db-url }}
        run: bundle exec rake cucumber

