name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:

jobs:
  cache-dependencies:
    name: Cache dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/ci-cache-dependencies.yaml@main

  security-analysis-ruby:
    name: Security Analysis Ruby
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/ci-security-analysis-ruby.yaml@main

  lint-scss:
    name: Lint SCSS
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/ci-lint-scss.yaml@main

  lint-javascript:
    name: Lint JavaScript
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/ci-lint-javascript.yaml@main

  lint-ruby:
    name: Lint Ruby
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/ci-lint-ruby.yaml@main

  test-javascript:
    name: Test JavaScript
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/ci-test-javascript.yaml@main

  test-ruby:
    name: Test Ruby
    needs: cache-dependencies
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      GOVUK_CONTENT_SCHEMAS_PATH: vendor/publishing-api/content_schemas
    steps:
      - name: Setup MySQL
        id: setup-mysql
        uses: alphagov/govuk-infrastructure/.github/actions/setup-mysql@composite-actions

      - name: Install additional system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ghostscript

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout Publishing API (for Content Schemas)
        uses: actions/checkout@v3
        with:
          repository: alphagov/publishing-api
          ref: deployed-to-production
          path: vendor/publishing-api

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Install JavaScript dependencies
        run: yarn install --frozen-lockfile

      - name: Initialize database
        env:
          TEST_DATABASE_URL: ${{ steps.setup-mysql.outputs.db-url }}
        run: bundle exec rails db:setup

      - name: Run tests
        env:
          TEST_DATABASE_URL: ${{ steps.setup-mysql.outputs.db-url }}
        run: bundle exec rake test
