name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - "Jenkinsfile"
      - ".git**"
  pull_request:

jobs:
  security-analysis:
    name: Security Analysis
    uses: alphagov/govuk-infrastructure/.github/workflows/brakeman.yml@main

  lint-scss:
    name: Lint SCSS
    uses: alphagov/govuk-infrastructure/.github/workflows/stylelint.yml@main
    with:
      files: "app/assets/stylesheets/"

  lint-javascript:
    name: Lint JavaScript
    uses: alphagov/govuk-infrastructure/.github/workflows/standardx.yml@main
    with:
      files: "'app/assets/javascripts/**/*.js' 'spec/javascripts/**/*.js'"

  lint-ruby:
    name: Lint Ruby
    uses: alphagov/govuk-infrastructure/.github/workflows/rubocop.yml@main

  test-javascript:
    name: Test JavaScript
    uses: alphagov/govuk-infrastructure/.github/workflows/jasmine.yml@main
    with:
      useWithRails: true

  pact-tests:
    name: Run Pact tests
    uses: ./.github/workflows/pact-verify.yml
    with:
      ref: ${{ github.ref }}

  test-ruby:
    name: Test Ruby
    uses: ./.github/workflows/minitest.yml

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup MySQL
        id: setup-mysql
        uses: alphagov/govuk-infrastructure/.github/actions/setup-mysql@main

      - name: Setup Redis
        uses: alphagov/govuk-infrastructure/.github/actions/setup-redis@main

      - name: Install additional system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ghostscript

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: alphagov/govuk-infrastructure/.github/actions/setup-node@main

      - name: Precompile assets
        uses: alphagov/govuk-infrastructure/.github/actions/precompile-rails-assets@main

      - name: Initialize database
        env:
          RAILS_ENV: test
          TEST_DATABASE_URL: ${{ steps.setup-mysql.outputs.db-url }}
        run: bundle exec rails db:setup

      - name: Run cucumber
        env:
          RAILS_ENV: test
          TEST_DATABASE_URL: ${{ steps.setup-mysql.outputs.db-url }}
        run: bundle exec rails cucumber

  # This job exists to satisfy branch protection rules enforced by govuk-saas-config.
  # It must be called "test" because that's what govuk-saas-config expects. [1]
  # It depends on all the preceeding CI jobs, so PRs can only be merged once everything else has passed.
  # This workaround should only be needed short-term because it's on the #govuk-replatforming team's radar to fix. [2]
  # [1]: https://github.com/alphagov/govuk-saas-config/blob/7879273/github/lib/configure_repo.rb#L106
  # [2]: https://gds.slack.com/archives/CD6JUFXML/p1680003969135179?thread_ts=1680003113.239669&cid=CD6JUFXML
  test:
    needs:
      - security-analysis
      - lint-scss
      - lint-javascript
      - lint-ruby
      - test-javascript
      - pact-tests
      - test-ruby
      - integration-tests
    runs-on: ubuntu-latest
    steps:
      - run: echo "All CI tests have passed 🚀"
